import { erc20ABI } from "./erc20ABI";
import { vaultV1ABI } from "./vaultV1ABI";
import { vaultV2ABI } from "./vaultV2ABI";
import { balancerProxyABI } from "./balancerProxyABI";
import { earnABI } from "./earnABI";
import { comptrollerABI } from "./comptrollerABI";
import { creamPriceOracleABI } from "./creamPriceOracleABI";
import { cERC20DelegatorABI } from "./cERC20DelegatorABI";
import { lockupABI } from "./lockupABI";
import { votingEscrowABI } from "./votingEscrowABI";
import { cdpVaultABI } from "./cdpVaultABI";
import { keep3rV1OracleABI } from "./keep3rV1OracleABI";
import { oracleRegistryABI } from "./oracleRegistryABI";
import { vaultManagerParamsABI } from "./vaultManagerParamsABI";
import { vaultParametersABI } from "./vaultParametersABI";
import { ltvMaximizerABI } from "./ltvMaximizerABI";
import { vaultManagerKeep3rSushiSwapMainAssetABI } from "./vaultManagerKeep3rSushiSwapMainAssetABI";
import { vaultManagerKeep3rMainAssetABI } from "./vaultManagerKeep3rMainAssetABI";
import { vaultMangerStandardABI } from "./vaultMangerStandardABI";
import { collateralRegistryABI } from "./collateralRegistryABI";
import { uniswapPairABI } from "./uniswapPairABI";
import { chainlinkOracleABI } from "./chainlinkOracleABI";

export const ERC20ABI = erc20ABI;
export const VAULTV1ABI = vaultV1ABI;
export const VAULTV2ABI = vaultV2ABI;
export const BALANCERPROXYABI = balancerProxyABI;
export const EARNABI = earnABI;
export const COMPTROLLERABI = comptrollerABI;
export const CREAMPRICEORACLEABI = creamPriceOracleABI;
export const CERC20DELEGATORABI = cERC20DelegatorABI;
export const LOCKUPABI = lockupABI;
export const VOTINGESCROWABI = votingEscrowABI;
export const CDPVAULTABI = cdpVaultABI;
export const KEEP3RV1ORACLEABI = keep3rV1OracleABI;
export const ORACLEREGISTRYABI = oracleRegistryABI;
export const VAULTMANAGERPARAMSABI = vaultManagerParamsABI;
export const VAULTPARAMETERSABI = vaultParametersABI;
export const LTVMAXIMIZERABI = ltvMaximizerABI;
export const VAULTMANAGERKEEP3RSUSHIABI = vaultManagerKeep3rSushiSwapMainAssetABI;
export const VAULTMANAGERKEEP3RABI = vaultManagerKeep3rMainAssetABI;
export const VAULTMANAGERSTANDARDABI = vaultMangerStandardABI;
export const COLLATERALREGISTRYABI = collateralRegistryABI;
export const UNISWAPPAIRABI = uniswapPairABI;
export const CHAINLINKORACLEABI = chainlinkOracleABI;
